apiVersion: apps/v1
kind: Deployment
metadata:
  name: seto-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seto-app
  template:
    metadata:
      labels:
        app: seto-app
    spec:
      containers:
      - name: seto-app
        image: 447655430298.dkr.ecr.ap-south-1.amazonaws.com/seto-app:latest
        ports:
        - containerPort: 5000