executor: LocalExecutor

redis:
  enabled: false

flower:
  enabled: false

triggerer:
  enabled: false

postgresql:
  enabled: true
  persistence:
    enabled: false

web:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi

scheduler:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
